from typing import Awaitable, Callable, Dict

__all__ = ['retry_http_async', 'retry_empty_dict_async', 'retry_json_error_async', 'retry_on_exception_async']

async def retry_http_async(func: Callable[..., Awaitable], *, retries: int=3, sleep: float=0.4) -> Callable[..., Awaitable]: ...
async def retry_empty_dict_async(func: Callable[..., Awaitable[Dict]], *, retries: int=3) -> Callable[..., Awaitable[Dict]]: ...
async def retry_json_error_async(func: Callable[..., Awaitable], *, retries: int=3) -> Callable[..., Awaitable]: ...
async def retry_on_exception_async(func: Callable[..., Awaitable], *, retries: int=3) -> Callable[..., Awaitable]: ...
